In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter(action='ignore')

In [2]:
data = pd.read_csv(r"C:\Users\ramba\OneDrive\Documents\AI\Lab 21 House_Rent_Dataset.csv")
data.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

In [3]:
data.columns

Index(['Posted On', 'BHK', 'Rent', 'Size', 'Floor', 'Area Type',
       'Area Locality', 'City', 'Furnishing Status', 'Tenant Preferred',
       'Bathroom', 'Point of Contact'],
      dtype='object')

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4746 entries, 0 to 4745
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Posted On          4746 non-null   object
 1   BHK                4746 non-null   int64
 2   Rent               4746 non-null   int64
 3   Size               4746 non-null   int64
 4   Floor              4746 non-null   object
 5   Area Type          4746 non-null   object
 6   Area Locality      4746 non-null   object
 7   City               4746 non-null   object
 8   Furnishing Status  4746 non-null   object
 9   Tenant Preferred   4746 non-null   object
 10  Bathroom           4746 non-null   int64
 11  Point of Contact   4746 non-null   object
dtypes: int64(4), object(8)
memory usage: 445.1+ KB

In [6]:
data = data.drop(['Posted on','Floor','Area Locality'], axis=1,errors='ignore')
data

,Posted On,BHK,Rent,Size,Area Type,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Super Area,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,Super Area,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,Super Area,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,Super Area,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,Carpet Area,Kolkata,Unfurnished,Bachelors,1,Contact Owner
...,...,...,...,...,...,...,...,...,...,...
4741,2022-05-18,2,15000,1000,Carpet Area,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4742,2022-05-15,3,29000,2000,Super Area,Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
4743,2022-07-10,3,35000,1750,Carpet Area,Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
4744,2022-07-06,3,45000,1500,Carpet Area,Hyderabad,Semi-Furnished,Family,2,Contact Agent
4745,2022-05-04,2,15000,1000,Carpet Area,Hyderabad,Unfurnished,Bachelors,2,Contact Owner

In [7]:
!pip install category-encoders

Collecting category-encoders
  Downloading category_encoders-2.9.0-py3-none-any.whl.metadata (7.9 kB)
Requirement already satisfied: numpy>=1.14.0 in c:\users\ramba\anaconda3\lib\site-packages (from category-encoders) (2.3.5)
Requirement already satisfied: pandas>=1.0.5 in c:\users\ramba\anaconda3\lib\site-packages (from category-encoders) (2.3.3)
Requirement already satisfied: patsy>=0.5.1 in c:\users\ramba\anaconda3\lib\site-packages (from category-encoders) (1.0.1)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\ramba\anaconda3\lib\site-packages (from category-encoders) (1.7.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\ramba\anaconda3\lib\site-packages (from category-encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\ramba\anaconda3\lib\site-packages (from category-encoders) (0.14.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ramba\anaconda3\lib\site-packages (from pandas>=1.0.5->category-encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ramba\anaconda3\lib\site-packages (from pandas>=1.0.5->category-encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ramba\anaconda3\lib\site-packages (from pandas>=1.0.5->category-encoders) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\ramba\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category-encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\ramba\anaconda3\lib\site-packages (from scikit-learn>=1.6.0->category-encoders) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\ramba\anaconda3\lib\site-packages (from scikit-learn>=1.6.0->category-encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in c:\users\ramba\anaconda3\lib\site-packages (from statsmodels>=0.9.0->category-encoders) (25.0)
Downloading category_encoders-2.9.0-py3-none-any.whl (85 kB)
Installing collected packages: category-encoders
Successfully installed category-encoders-2.9.0