In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score,GridSearchCV

import sklearn.metrics as metrics

import category_encoders as metrics

import category_encoders as ce
from sklearn.preprocessing import MinMaxScaler

In [4]:
data = pd.read_csv(r"C:\Users\ramba\OneDrive\Documents\AI\Lab 21 House_Rent_Dataset.csv")
data.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

In [5]:
data = data.drop(['Posted on','Floor','Area Locality'], axis=1,errors='ignore')
data

,Posted On,BHK,Rent,Size,Area Type,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Super Area,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,Super Area,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,Super Area,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,Super Area,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,Carpet Area,Kolkata,Unfurnished,Bachelors,1,Contact Owner
...,...,...,...,...,...,...,...,...,...,...
4741,2022-05-18,2,15000,1000,Carpet Area,Hyderabad,Semi-Furnished,Bachelors/Family,2,Contact Owner
4742,2022-05-15,3,29000,2000,Super Area,Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Owner
4743,2022-07-10,3,35000,1750,Carpet Area,Hyderabad,Semi-Furnished,Bachelors/Family,3,Contact Agent
4744,2022-07-06,3,45000,1500,Carpet Area,Hyderabad,Semi-Furnished,Family,2,Contact Agent
4745,2022-05-04,2,15000,1000,Carpet Area,Hyderabad,Unfurnished,Bachelors,2,Contact Owner

In [6]:
!pip install category-encoders

Requirement already satisfied: category-encoders in c:\users\ramba\anaconda3\lib\site-packages (2.9.0)
Requirement already satisfied: numpy>=1.14.0 in c:\users\ramba\anaconda3\lib\site-packages (from category-encoders) (2.3.5)
Requirement already satisfied: pandas>=1.0.5 in c:\users\ramba\anaconda3\lib\site-packages (from category-encoders) (2.3.3)
Requirement already satisfied: patsy>=0.5.1 in c:\users\ramba\anaconda3\lib\site-packages (from category-encoders) (1.0.1)
Requirement already satisfied: scikit-learn>=1.6.0 in c:\users\ramba\anaconda3\lib\site-packages (from category-encoders) (1.7.2)
Requirement already satisfied: scipy>=1.0.0 in c:\users\ramba\anaconda3\lib\site-packages (from category-encoders) (1.16.3)
Requirement already satisfied: statsmodels>=0.9.0 in c:\users\ramba\anaconda3\lib\site-packages (from category-encoders) (0.14.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ramba\anaconda3\lib\site-packages (from pandas>=1.0.5->category-encoders) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ramba\anaconda3\lib\site-packages (from pandas>=1.0.5->category-encoders) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ramba\anaconda3\lib\site-packages (from pandas>=1.0.5->category-encoders) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\ramba\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->category-encoders) (1.17.0)
Requirement already satisfied: joblib>=1.2.0 in c:\users\ramba\anaconda3\lib\site-packages (from scikit-learn>=1.6.0->category-encoders) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\ramba\anaconda3\lib\site-packages (from scikit-learn>=1.6.0->category-encoders) (3.5.0)
Requirement already satisfied: packaging>=21.3 in c:\users\ramba\anaconda3\lib\site-packages (from statsmodels>=0.9.0->category-encoders) (25.0)

In [7]:
categorical_cols = data.select_dtypes(include="object").columns
categorical_cols

Index(['Posted On', 'Area Type', 'City', 'Furnishing Status',
       'Tenant Preferred', 'Point of Contact'],
      dtype='object')

In [8]:
for col in categorical_cols:
    print(f"{col}:{data[col].nunique()}")

Posted On:81
Area Type:3
City:6
Furnishing Status:3
Tenant Preferred:3
Point of Contact:3

In [9]:
x=data.drop(columns="Rent")
y=data["Rent"]

In [10]:
encoder = ce.LeaveOneOutEncoder(return_df=True)
x=encoder.fit_transform(x,y)

In [11]:
x.head()

,Posted On,BHK,Size,Area Type,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,49986.301370,2,1100,18676.943967,11648.319312,22468.505513,31216.953238,2,16706.291757
1,33369.521739,2,800,18672.853988,11629.198853,38727.130222,31214.048795,1,16703.181337
2,22156.603774,2,1000,18674.080982,11634.934990,38728.463556,31214.920128,1,16704.114463
3,36085.321101,2,800,18676.943967,11648.319312,22468.505513,31216.953238,1,16706.291757
4,15857.142857,2,850,52405.438398,11653.099426,22469.883682,42185.583836,1,16707.069362

In [12]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
x = scaler.fit_transform(x)

In [13]:
x_df = pd.DataFrame(x)
x_df

,0,1,2,3,4,5,6,7,8
0,0.455100,0.2,0.136421,0.273162,0.004388,0.009553,0.017960,0.111111,0.003219
1,0.270592,0.2,0.098874,0.273074,0.004130,0.487075,0.017809,0.000000,0.003165
2,0.146087,0.2,0.123905,0.273100,0.004207,0.487114,0.017854,0.000000,0.003181
3,0.300748,0.2,0.098874,0.273162,0.004388,0.009553,0.017960,0.000000,0.003219
4,0.076140,0.2,0.105131,0.999941,0.004452,0.009593,0.587919,0.000000,0.003233
...,...,...,...,...,...,...,...,...,...
4741,0.454339,0.2,0.123905,0.999871,0.124704,0.487140,0.017884,0.111111,0.003192
4742,0.069530,0.4,0.249061,0.272994,0.124486,0.486957,0.017673,0.222222,0.003116
4743,0.352491,0.4,0.217772,0.999683,0.124392,0.486879,0.017582,0.222222,0.999656
4744,0.433114,0.4,0.186483,0.999589,0.124236,0.486748,0.995587,0.111111,0.999541
4745,0.116897,0.2,0.123905,0.999871,0.124704,0.009472,0.587449,0.111111,0.003192