In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.simplefilter(action = 'ignore')

In [2]:
data = pd.read_csv(r"C:\Users\ramba\OneDrive\Documents\AI\Lab 21 House_Rent_Dataset.csv")
data.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner

In [3]:
from sklearn.svm import SVR
from sklearn.model_selection  import train_test_split
from sklearn.model_selection import cross_val_score,GridSearchCV

import sklearn.metrics as metrics

import category_encoders as ce
from sklearn.preprocessing import MinMaxScaler

In [4]:
categorical_cols = data.select_dtypes(include = "object").columns
categorical_cols

Index(['Posted On', 'Floor', 'Area Type', 'Area Locality', 'City',
       'Furnishing Status', 'Tenant Preferred', 'Point of Contact'],
      dtype='object')

In [5]:
for col in categorical_cols:
    print(f"{col}:{data[col].nunique()}")

Posted On:81
Floor:480
Area Type:3
Area Locality:2235
City:6
Furnishing Status:3
Tenant Preferred:3
Point of Contact:3

In [6]:
x = data.drop(columns = "Rent")
y = data["Rent"]

In [7]:
encoder = ce.LeaveOneOutEncoder(return_df = True)
x = encoder.fit_transform(x,y)

In [8]:
x.head()

,Posted On,BHK,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,49986.301370,2,1100,14164.719198,18676.943967,6500.000000,11648.319312,22468.505513,31216.953238,2,16706.291757
1,33369.521739,2,800,17947.602740,18672.853988,3500.000000,11629.198853,38727.130222,31214.048795,1,16703.181337
2,22156.603774,2,1000,17957.876712,18674.080982,23600.000000,11634.934990,38728.463556,31214.920128,1,16704.114463
3,36085.321101,2,800,14458.465608,18676.943967,22000.000000,11648.319312,22468.505513,31216.953238,1,16706.291757
4,15857.142857,2,850,14465.079365,52405.438398,34993.451327,11653.099426,22469.883682,42185.583836,1,16707.069362

In [9]:
from  sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X = scaler.fit_transform(x)

In [17]:
x_df = pd.DataFrame(X)
x_df

,0,1,2,3,4,5,6,7,8,9,10
0,0.455100,0.2,0.136421,0.011747,0.273162,0.005055,0.004388,0.009553,0.017960,0.111111,0.003219
1,0.270592,0.2,0.098874,0.017362,0.273074,0.001685,0.004130,0.487075,0.017809,0.000000,0.003165
2,0.146087,0.2,0.123905,0.017377,0.273100,0.024264,0.004207,0.487114,0.017854,0.000000,0.003181
3,0.300748,0.2,0.098874,0.012183,0.273162,0.022466,0.004388,0.009553,0.017960,0.000000,0.003219
4,0.076140,0.2,0.105131,0.012193,0.999941,0.037062,0.004452,0.009593,0.587919,0.000000,0.003233
...,...,...,...,...,...,...,...,...,...,...,...
4741,0.454339,0.2,0.123905,0.023746,0.999871,0.016288,0.124704,0.487140,0.017884,0.111111,0.003192
4742,0.069530,0.4,0.249061,0.028006,0.272994,0.037062,0.124486,0.486957,0.017673,0.222222,0.003116
4743,0.352491,0.4,0.217772,0.023389,0.999683,0.031453,0.124392,0.486879,0.017582,0.222222,0.999656
4744,0.433114,0.4,0.186483,0.042662,0.999589,0.046999,0.124236,0.486748,0.995587,0.111111,0.999541
4745,0.116897,0.2,0.123905,0.018618,0.999871,0.015446,0.124704,0.009472,0.587449,0.111111,0.003192

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=40
)

In [14]:
model = SVR()

In [20]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [22]:
model_svr = SVR(
    kernel = 'rbf',
    C = 100,
    gamma = 'scale',
    epsilon = 0.01
)

model_svr.fit(X_train,y_train)

SVR(C=100, epsilon=0.01)

In [23]:
y_pred = model_svr.predict(X_test)

# Evaluation Metrics
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

# Print Results
print("\nModel Performance")
print("-" * 30)
print("Mean Absolute Error (MAE):", mae)
print("Mean Squared Error (MSE):", mse)
print("Root Mean Squared Error (RMSE):", rmse)
print("R2 Score:", r2)

Model Performance
------------------------------
Mean Absolute Error (MAE): 15886.984738713958
Mean Squared Error (MSE): 2882063281.5231323
Root Mean Squared Error (RMSE): 53684.85150881142
R2 Score: 0.1274920354314929